#!/usr/bin/env bash

set -x

# Uncomment to refresh ubersicht widget on workspace change -- from aspect dots
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ===== Tiling setting =========================

yabai -m config \
  layout bsp \
  \
  external_bar all:30:0 \
  \
  top_padding 8 \
  bottom_padding 10 \
  left_padding 11 \
  right_padding 11 \
  window_gap 8 \
  \
  mouse_follows_focus off \
  focus_follows_mouse off \
  \
  window_topmost on \
  window_opacity off \
  window_shadow on \
  \
  window_border off \
  window_border_blur off \
  window_border_hidpi on \
  window_border_width 3 \
  window_border_radius 11 \
  window_origin_display default \
  window_placement second_child \
  window_topmost off \
  \
  insert_feedback_color "0xaad75f5f" \
  active_window_border_color "0xfff4dbd6" \
  normal_window_border_color "0x8f363a4f" \
  \
  window_opacity off \
  active_window_opacity 1.0 \
  normal_window_opacity 0.8 \
  \
  window_animation_duration 0.01 \
  \
  split_ratio 0.63 \
  \
  auto_balance off \
  \
  mouse_modifier ctrl \
  mouse_action1 move \
  mouse_action2 stack

# ===== Rules ==================================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Settings)" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Raycast Settings" app="Raycast" title=".*" manage=off
yabai -m rule --add label="FaceTime" app="FaceTime" title=".*" manage=off

yabai -m rule --add app="Arc.LittleBrowserWindow" manage=off
yabai -m rule --add label="Little Arc" app="^Arc$" title="^Little\sArc.*" manage=off
yabai -m rule --add label="Little Arc" app="^Arc$" title="^Space.*" manage=off
yabai -m rule --add app="^Arc$" title="^$" mouse_follows_focus=off
# ===== Signals ================================
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_created action="yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er '.\"can-resize\" == false and .\"is-floating\" == false' && yabai -m window $YABAI_WINDOW_ID --toggle float"

# ===== Sketchybar Events ======================

# yabai -m signal --add event=window_focused       action="sketchybar -m --trigger window_focus"
# yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change"

# ===== Spaces =================================
yabai -m space 1 --label emacs
yabai -m space 2 --label terminal
yabai -m space 3 --label browser
yabai -m space 4 --label pdf/rss
yabai -m space 5 --label mail
yabai -m space 6 --label ...

# yabai -m rule --add app="kitty" space=terminal
# yabai -m rule --add app="Arc" space=browser
yabai -m rule --add app="Mail" space=mail

set +x
printf "yabai: configuration loaded...\\n"
